<?php

/**
 * @file
 * Populate Hedley content.
 */

/**
 * Implements hook_migrate_api().
 */
function hedley_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'HedleyCompaniesMigrate',
    'HedleyEventsMigrate',
    // Users.
    'HedleyUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
